name: CI dev

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('yarn.lock') }}

      - name: Yarn install
        run: yarn

      - name: Build
        run: yarn build:dev

      - name: Build and deploy the package to AWS
        run: SLS_DEBUG=* ./node_modules/serverless/bin/serverless.js deploy --verbose --stage dev
        env:
          FRONTEND_DOMAIN: dev.my-site.com
